### PR TITLE
Fixes #84: use correct operator for pattern constraint

### LINKED ISSUE #84: Pattern check uses 'like' which is not RE compatible
# Overview

In version 1.3.0, constraint checks were added.

The `pattern` constraint, though, was implemented using a `like` sql operator which is not POSIX RE compatible:

https://github.com/frictionlessdata/tableschema-sql-py/commit/11b41b27a991a347b9117ae312f2e1dd0ccb4fca#diff-06244424627478397c4e73620b8d452fR72

From the postgresql documentation, the correct operator should probably have been `~`.

Please preserve this line to notify @roll (lead of this repository)

### PR DESCRIPTION
**Pull request by akariv**
# Overview

Please replace this line with full information about your pull request. Make sure that tests pass before publishing it

---

Please preserve this line to notify @roll (lead of this repository)

### CODE REVIEW

**Comment by roll** [comment]
@akariv 
Is there is a way to have this `sqlite3-pcre` installed via pip? We can't rely on its existence. And I think we need to skip the `check` if not available (for sqlite).

**Comment by akariv** [comment]
Tbh I would skip it either way as it's not natively supported by sqlite.
Wdyt?

**Comment by roll** [comment]
@akariv 
I agree. Let's skip.

**Comment by akariv** [comment]
Okay, I found a workaround - see the tests code for an example

**Comment by akariv** [comment]
^ @roll

**Comment by roll** [comment]
you made it :smiley:

**Review by roll — APPROVED** [review]

**Pull request merged**
