### PR TITLE
Enhance/write transaction

### LINKED ISSUE #8: Improve memory usage
- [x] use stream in `Storage.write()` or write by chunks (#29)
- [x] investigate memory usage in `Storage.read()` (possible SQLAlchemy bug)

### PR DESCRIPTION
**Pull request by roll**
- added transaction to `Storage.write`

---
- fixes #8

### CODE REVIEW

**Comment by roll** [comment]
@akariv please take a look

**Comment by akariv** [comment]
Looks good. Do we want to add a test that this is actually working?

**Comment by roll** [comment]
You mean rollback? Good idea) will do

**Comment by roll** [comment]
@akariv added bigdata and bigdata rollback tests

**Comment by akariv** [comment]
Great, no comments.

**Pull request merged**
